name: 🚀 Deploy website to prod on merge

on:
  pull_request:
    types: [ closed ]
    branches:
      - main
jobs:
  web-deploy:
    if: github.event.pull_request.merged == true
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
      - name: "Use Node.js"
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Install dependencies and run Gulp on theme
        working-directory: "./wp-content/themes/greeneis/"
        run: |
          npm i
          gulp build
          rm -rf node_modules
      - name: Upload All Files
        uses: appleboy/scp-action@master
        with:
          timeout: 200s
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USER_LOGIN }}
          port: ${{ secrets.SSH_PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "wp-content/*"
          target: "~/domains/greeneis.vvweb.top/public_html"
